version: "3"

services:
  #############################
  # ELASTICSEARCH MASTER NODE #
  #############################
  elasticsearch:
    restart: unless-stopped
    image: blacktop/elasticsearch:6.7
    environment:
      - cluster.name=docker-cluster
      - network.host=0
      - ELASTIC_PASSWORD=pleasechangeme
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
    ports:
      - "9200:9200"

  ###############
  # KIBANA NODE #
  ###############
  kibana:
    image: blacktop/kibana:6.7
    environment:
      - elasticsearch.url=http://elasticsearch:9200
      - elasticsearch.username=elastic
      - elasticsearch.password=pleasechangeme
    ports:
      - "80:5601"
    links:
     - elasticsearch

  textbox1:
    image: &tb-image
      machinebox/textbox:latest
    environment: &tb-environment
      - MB_KEY=ZjZiNzBjYWVjMmQyNDdmY2FjY2M4YmM1MTQyZWJjY2I.38ZQXpozRNZJROnTWCTecxrmWEQf2T6pjRzlROrDgHlL7_AKvv_AG8YW-Ahh5DBx88wi1XF3QXCOmoa_RaSyVw
      - MB_PORT=3000
      - PORT=3000

  textbox2:
    image: *tb-image
    environment: *tb-environment

  loadbalancer:
    image: nimmis/alpine-nginx
    tty: true
    links:
      - textbox1
      - textbox2
    ports:
      - '8080:8080'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

#############################
# ELASTICSEARCH DATA VOLUME #
#############################
# volumes:
#   data:
